/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include <stdio.h>

// LED 설정
#define PORT10_BASE (0xF003B000)
#define PORT02_BASE (0xF003A200)
#define PORT10_IOCR0 (*(volatile unsigned int*)(PORT10_BASE + 0x10))
#define PORT02_IOCR0 (*(volatile unsigned int*)(PORT02_BASE + 0x10))
#define PORT10_IOCR4 (*(volatile unsigned int*)(PORT10_BASE + 0x14))
#define PORT02_IOCR4 (*(volatile unsigned int*)(PORT02_BASE + 0x14))
#define PORT10_OMR (*(volatile unsigned int*)(PORT10_BASE + 0x04))
#define PORT02_OMR (*(volatile unsigned int*)(PORT02_BASE + 0x04))
#define PORT02_IN (*(volatile unsigned int*)(PORT02_BASE + 0x24))

#define PC0 3
#define PC1 11
#define PC2 19
#define PC3 27
#define PC5 11
#define PC7 27

#define PCL1 17
#define PCL2 18
#define PCL3 19
#define PCL5 21
#define PCL7 23

#define PS1 1
#define PS2 2
#define PS3 3
#define PS5 5
#define PS7 7

#define P0 0
#define P1 1
#define P2 2

// SCU Switch EICR&IGCR 설정
#define SCU_BASE (0xF0036000)
#define SCU_EICR_1 (*(volatile unsigned int*)(SCU_BASE + 0x214))
#define SCU_IGCR_0 (*(volatile unsigned int*)(SCU_BASE + 0x22C))

#define EXIS0 4
#define FEN0 8
#define EIEN0 11
#define INP0 12
#define IGP0 14

#define EXIS1 20
#define FEN1 24
#define EIEN1 27
#define INP1 28
#define IGP1 30

// CCU60 Register 설정
#define CCU60_BASE    (0xF0002A00) //page 26-138
#define CCU60_CLC     (*(volatile unsigned int*)(CCU60_BASE + 0x00)) //page 26-128
#define CCU60_T12     (*(volatile unsigned int*)(CCU60_BASE + 0x20)) //page 26-5
#define CCU60_T12PR   (*(volatile unsigned int*)(CCU60_BASE + 0x24)) //page 26-5
#define CCU60_TCTR0   (*(volatile unsigned int*)(CCU60_BASE + 0x70)) //page 26-6
#define CCU60_TCTR4   (*(volatile unsigned int*)(CCU60_BASE + 0x78)) //page 26-6
#define CCU60_INP     (*(volatile unsigned int*)(CCU60_BASE + 0xAC)) //page 26-7
#define CCU60_IEN     (*(volatile unsigned int*)(CCU60_BASE + 0xB0)) //page 26-7

#define DISS    1 //page 26-130
#define DISR    0 //page 26-130
#define CTM     7
#define T12PRE  3
#define T12CLK  0
#define T12STR  6
#define T12RS   1
#define T12RR   0
#define INPT12  10
#define ENT12PM 7

// ADC 설정
#define VADC_BASE         (0xF0020000)
#define VADC_CLC          (*(volatile unsigned int*)(VADC_BASE + 0x000))
#define VADC_GLOBCFG      (*(volatile unsigned int*)(VADC_BASE + 0x080))
#define VADC_G4ARBCFG     (*(volatile unsigned int*)(VADC_BASE + 0x1480))
#define VADC_G4ARBPR      (*(volatile unsigned int*)(VADC_BASE + 0x1484))
#define VADC_G4ICLASS0    (*(volatile unsigned int*)(VADC_BASE + 0x14A0))
#define VADC_G4QMR0       (*(volatile unsigned int*)(VADC_BASE + 0x1504))
#define VADC_G4QINR0      (*(volatile unsigned int*)(VADC_BASE + 0x1510))
#define VADC_G4CHCTR7     (*(volatile unsigned int*)(VADC_BASE + 0x161C))
#define VADC_G4RES1       (*(volatile unsigned int*)(VADC_BASE + 0x1704))

//#define DISS    1 //page 26-130
//#define DISR    0 //page 26-130
#define ANONC     0
#define ASEN0     24
#define CSM0      3
#define PRIO0     0
#define CMS       8
#define STSC      0
#define FLUSH     10
#define TREV      9
#define ENGT      0
#define RF        5
#define REQCHNR   0
#define RESPOS    21
#define RESREG    16
#define ICLSEL    0
#define VF        31
#define RESULT    0

//GTM Register 설정
#define GTM_BASE                 (0xF0100000)
#define GTM_CMU_CLK_EN           (*(volatile unsigned int*)(GTM_BASE + 0x00300))
#define GTM_CMU_FXCLK_CTRL       (*(volatile unsigned int*)(GTM_BASE + 0x00344))

#define EN_FXCLK      22
#define FXCLK_SEL     0

//GTM TOM0
#define GTM_TOM0_TGC0_GLB_CTRL   (*(volatile unsigned int*)(GTM_BASE + 0x08030))
#define GTM_TOM0_TGC0_ENDIS_CTRL (*(volatile unsigned int*)(GTM_BASE + 0x08070))
#define GTM_TOM0_TGC0_OUTEN_CTRL (*(volatile unsigned int*)(GTM_BASE + 0x08078))
#define GTM_TOM0_TGC0_FUPD_CTRL  (*(volatile unsigned int*)(GTM_BASE + 0x08038))
#define GTM_TOM0_TGC0_CH1_CTRL   (*(volatile unsigned int*)(GTM_BASE + 0x08040))
#define GTM_TOM0_TGC0_CH1_SR0    (*(volatile unsigned int*)(GTM_BASE + 0x08044))
#define GTM_TOM0_TGC0_CH1_SR1    (*(volatile unsigned int*)(GTM_BASE + 0x08048))

#define UPEN_CTRL     18
#define HOST_TRIG     0
#define ENDIS_CTRL1   2
#define OUTEN_CTRL1   2
#define RSTCN0_CH1    18
#define FUPD_CTRL1    2
#define CLK_SRC_SR    12
#define SL            11

//GTM
#define GTM_CLC                 (*(volatile unsigned int*)(GTM_BASE + 0x9FD00))
#define GTM_TOUTSEL6            (*(volatile unsigned int*)(GTM_BASE + 0x9FD48))

#define SEL7          14



// 인터럽트 라우터 설정 (우선순위) - switch
#define SRC_BASE (0xF0038000)
#define SRC_SCUERU_0 (*(volatile unsigned int*)(SRC_BASE + 0xCD4))
#define SRC_SCUERU_1 (*(volatile unsigned int*)(SRC_BASE + 0xCD8))

// 인터럽트 라우터 설정 (우선순위) - timer
#define SRC_CCU60_SR0 (*(volatile unsigned int*)(SRC_BASE + 0x420))

#define TOS 11
#define SRE 10
#define SRPN 0

// SAFETY 설정
#define SCU_BASE (0xF0036000)
#define SCU_WDTSCON_0 (*(volatile unsigned int*)(SCU_BASE + 0x0F0)) // switch
#define SCU_WDT_CPU0CON0 (*(volatile unsigned int*)(SCU_BASE + 0x100)) // timer
#define LCK 1
#define ENDINIT 0



void init_LED(void);
void init_GTM_TOM0_PWM(void);
void init_VADC(void);
void VADC_startConversion(void);
unsigned int VADC_readResult(void);
unsigned int adcResult;



IfxCpu_syncEvent g_cpuSyncEvent = 0;

int core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);



    init_LED();
    init_GTM_TOM0_PWM();
    init_VADC();

    volatile int P_OUT;
    volatile int DUTY_exten;
    volatile float DUTY;
    float exten = 10000;


    while(1)
    {
        VADC_startConversion();

        adcResult = VADC_readResult();

        P_OUT = adcResult;
        DUTY_exten = ((adcResult * exten / 4095) * 12500);
        DUTY = DUTY_exten / exten ;

        if(DUTY >= 1)
        {

            GTM_TOM0_TGC0_CH1_SR1 = DUTY -1 ;
        }

        else
        {
            GTM_TOM0_TGC0_CH1_SR1 = 2 -1; // DUTY RATE를 설정 (0%)
        }


               if(adcResult >= 3410)
               {
                   GTM_TOM0_TGC0_CH1_SR1 = 12500 -1; // DUTY RATE를 설정 (100%)

               }
               else if(adcResult >= 2728)
               {
                   GTM_TOM0_TGC0_CH1_SR1 = 10000 -1; // DUTY RATE를 설정 (80%)
               }
               else if(adcResult >= 2046)
               {
                   GTM_TOM0_TGC0_CH1_SR1 = 7500 -1; // DUTY RATE를 설정 (60%)
               }
               else if(adcResult >= 1364)
               {
                   GTM_TOM0_TGC0_CH1_SR1 = 5000 -1; // DUTY RATE를 설정 (40%)
               }
               else if(adcResult >= 682)
               {
                   GTM_TOM0_TGC0_CH1_SR1 = 2500 -1; // DUTY RATE를 설정 (20%)

               }
               else
               {
                   GTM_TOM0_TGC0_CH1_SR1 = 1 -1; // DUTY RATE를 설정 (0%)

               }

    }
    return (1);
}



void init_LED()
    {

    PORT10_IOCR0 &= ~((0x1F) << PC1); // LED_RED

    PORT10_IOCR0 |= ((0x11) << PC1); // GTM의 TOUT103으로 출력신호 설정

    }

void init_GTM_TOM0_PWM(void)
    {

    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) != 0);

    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) | (1 << LCK)) & ~(1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) == 0);


    GTM_CLC &= ~(1 << DISR);   // ADC 모듈 활성화 (enable)


    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) != 0);

    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) | (1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) == 0);


    while((GTM_CLC & (1 << DISS)) != 0);   // GMT 모듈 활성화 완료 되었는지 확인

    //GMT CLOCK SETTING

    GTM_CMU_FXCLK_CTRL &= ~((0xF) << FXCLK_SEL); //GTM 내부 Fixed clock dirver 의 MUX(먹스)설정 = 0번 글로벌로

    GTM_CMU_CLK_EN &= ~((0x3) << EN_FXCLK); // FXU 모듈 enable
    GTM_CMU_CLK_EN |= ((0x2) << EN_FXCLK);

    GTM_TOM0_TGC0_GLB_CTRL &= ~((0x3) << UPEN_CTRL); // CM0, CM1, SRC 값 업데이트 enable 설정
    GTM_TOM0_TGC0_GLB_CTRL |= ((0x2) << UPEN_CTRL); // 11로 업데이트 enable설정

    GTM_TOM0_TGC0_FUPD_CTRL &= ~((0x3) << FUPD_CTRL1); // CM0, CM1, SRC 값이 트리거 신호에 의해 업데이트 되도록 설정
    GTM_TOM0_TGC0_FUPD_CTRL |= ((0x2) << FUPD_CTRL1);  // 10 is enable
    GTM_TOM0_TGC0_FUPD_CTRL &= ~((0x3) << RSTCN0_CH1); // 트리서 신호에 의해 CN0 값 리셋 (카운트 값 리셋) 되도록 설정
    GTM_TOM0_TGC0_FUPD_CTRL |= ((0x2) << RSTCN0_CH1);

    GTM_TOM0_TGC0_ENDIS_CTRL &= ~((0x3) << ENDIS_CTRL1);  // 해당 체널(1번) Enable 설정
    GTM_TOM0_TGC0_ENDIS_CTRL |= ((0x2) << ENDIS_CTRL1);
    GTM_TOM0_TGC0_OUTEN_CTRL &= ~((0x3) << OUTEN_CTRL1);   // 해당 체널 신호의 OUTPUT Enable 설정
    GTM_TOM0_TGC0_OUTEN_CTRL |= ((0x2) << OUTEN_CTRL1);

//    GTM_TOM0_TGC0_CH1_CTRL &= ((0x1) << SL); // 해당 체널의 DUTY CYCLE POLARITY(극성) 설정 (Low)
    GTM_TOM0_TGC0_CH1_CTRL |= ( 1 << SL); // 해당 체널의 DUTY CYCLE POLARITY(극성) 설정 (High)

    GTM_TOM0_TGC0_CH1_CTRL &= ~((0x7) << CLK_SRC_SR); // PWM 주파수 프리스케일링 (1/16 으로 설정)
    GTM_TOM0_TGC0_CH1_CTRL |= ((0x1) << CLK_SRC_SR); // 001 입력 (100MHz / 16 = 6,250kHz)
    GTM_TOM0_TGC0_CH1_SR0 = 12500 -1; // 주기를 2ms로 설정 (12500/6250kHz == 0.002s)
//    GTM_TOM0_TGC0_CH1_SR0 = 0;
//    GTM_TOM0_TGC0_CH1_SR0 = 6250 -1;
    GTM_TOM0_TGC0_CH1_SR1 = 12500 -1; // DUTY RATE를 설정 (100%)

    GTM_TOUTSEL6 &= ~((0x3) << SEL7); // TOUT3번의 아웃 출력 포트를 A로 설정
    GTM_TOM0_TGC0_GLB_CTRL |= ((0x1) << HOST_TRIG); // PWM 신호 작동 트리거 설정
    }

void init_VADC(void)
    {

    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) != 0);

    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) | (1 << LCK)) & ~(1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) == 0);


    VADC_CLC &= ~(1 << DISR);   // ADC 모듈 활성화 (enable)


    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) & ~(1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) != 0);

    SCU_WDT_CPU0CON0 = ((SCU_WDT_CPU0CON0 ^ 0xFC) | (1 << LCK)) | (1 << ENDINIT);
    while((SCU_WDT_CPU0CON0 & (1 << LCK)) == 0);


    while((VADC_CLC & (1 << DISS)) != 0);   // ADC 모듈 활성화 완료 되었는지 확인

    VADC_G4ARBPR |= ((0x3) << PRIO0); // 내가 사용하려는 Request Source관련 설정
                                      // 사용하려는 소스는 0번영역으로 설정, 해당 그룹의 저장공간에서의 그 소스 처리의 우선순위를 가장 높은 11로 설정
    VADC_G4ARBPR &= ~(1 << CSM0); // 새로 들어오는 소스의 데이터 저장을 기존 ADC동작 끝나고 최신화 하는지, 중간에 바로 최신화 하는지 설정의 초기화 작업. 0이 기존동작 유지
    VADC_G4ARBPR |= ( 1 << ASEN0); // 해당 리퀘스트 소스 Enable

    VADC_G4QMR0 &= ~((0x3) << ENGT); // 리퀘스트 소스의 동작 트리거 설정 (00/미동작, 01/(S/W)코딩에 의한 동작, 02~03/타이머나 외브 OI에 의한 동작
    VADC_G4QMR0 |= ( 1 << ENGT); //

    VADC_G4QMR0 |= ( 1 << FLUSH); // ADC 동작 시, 기존 데이터 베이스 삭제 유무 (00/안함, 01/클리어)

    VADC_G4ARBCFG |= ((0x3) << ANONC); // 그룹4의 ADC 동작방법 설정 (저전력을 위해, 트리거가 들어오기 전까지 ADC 슬립모드 == 일반동작 모드, 11적용)

    VADC_G4ICLASS0 &= ~((0x7) << CMS); //컨버전 모드 (얼라인 크기 설정)

    // 7번 체널에 대한 설정
    VADC_G4CHCTR7 |= (1 << RESPOS); // 얼라인 방법 (왼쪽 정렬 or 오른쪽 정렬)
    VADC_G4CHCTR7 &= ~((0xF) << RESREG);
    VADC_G4CHCTR7 |= (1 << RESREG); //  해당 그룹의 저장소 중 저장할 영역을 1번으로 설정 (0~15중 선택)
    VADC_G4CHCTR7 &= ~((0x3) << ICLSEL); // 데이터가 저장되는 그룹 설정 (글로벌 말로 그룹마다 할당되어 있는 영역 중 00번으로 설정)

    }

void VADC_startConversion(void)
    {

    VADC_G4QINR0 &= ~(0x1F); //사용할 체널 정보 변경 과정(클리어)
    VADC_G4QINR0 |= (0x07);  //체널 7번 입력

    VADC_G4QINR0 &= ~(1 << RF); // 트리거 발동 후, ADC 동작을 한번만 하냐, 연속동작하냐 (0이면 한번만, 1이면 계속)

    VADC_G4QMR0 |= (1 << TREV); // 이벤트 시작 트리거 발동

    }

//저장소의 저장방법 설정
unsigned int VADC_readResult(void)
    {
    unsigned int result;
    while((VADC_G4RES1 & (1 <<VF)) == 0); // ADC 로 인해 새로운값이 리플레이스 되었는지 확인 (확인작업 누락하면 그냥 지금까지 저장된놈 강제 불러옴)
    result = (VADC_G4RES1 & (0xFFFF << RESULT)); // 저장소에 저장된 값을 변수에 저장

    return result;
    }
